---
- name: R0
  id: 1
  management_ip: "172.31.178.1"
- name: S0
  id: 2
  management_ip: "172.31.178.2"
- name: S1
  id: 3
  management_ip: "172.31.178.3"
- name: R1
  id: 4
  management_ip: "172.31.178.4"
- name: R2
  id: 5
  management_ip: "172.31.178.5"
- name: R3
  id: 6
  management_ip: "172.31.178.6"
- name: R4
  id: 7
  management_ip: "172.31.178.7"
- name: S2
  id: 8
  management_ip: "172.31.178.8"
- name: R5
  id: 9
  management_ip: "172.31.178.9"
