---
- name: R0
  id: 1
  management_ip: "172.31.178.1"
  loopback: true
  interfaces:
    - id: 1
      name: "g0/1"
      ip: "10.0.15.178"
      subnet: "255.255.255.0"
      desc: "Connect to Cloud1"
- name: S0
  id: 2
  management_ip: "172.31.178.2"
  loopback: true
  interfaces:
- name: S1
  id: 3
  management_ip: "172.31.178.3"
  loopback: true
  interfaces:
- name: R1
  id: 4
  management_ip: "172.31.178.4"
  loopback: true
  interfaces:
    - name: "g0/1"
      ip: "172.31.178.17"
      subnet: "255.255.255.240"
      desc: "Connect to R2 (172.31.178.16/28)"
    - name: "g0/2"
      ip: "172.31.178.33"
      subnet: "255.255.255.240"
      desc: "Connect to R3 (172.31.178.32/28)"
- name: R2
  id: 5
  management_ip: "172.31.178.5"
  loopback: true
  interfaces:
    - name: "g0/1"
      ip: "172.31.178.18"
      subnet: "255.255.255.240"
      desc: "Connect to R1 (172.31.178.16/28)"
    - name: "g0/2"
      ip: "172.31.178.49"
      subnet: "255.255.255.240"
      desc: "Connect to R3 (172.31.178.48/28)"
- name: R3
  id: 6
  management_ip: "172.31.178.6"
  loopback: true
  interfaces:
    - name: "g0/1"
      ip: "172.31.178.34"
      subnet: "255.255.255.240"
      desc: "Connect to R1 (172.31.178.32/28)"
    - name: "g0/2"
      ip: "172.31.178.50"
      subnet: "255.255.255.240 (172.31.178.48/28)"
      desc: "Connect to R2"
    - name: "g0/3"
      ip: "172.31.178.65"
      subnet: "255.255.255.240"
      desc: "Connect to R4 and R5 (172.31.178.64/28)"
- name: R4
  id: 7
  management_ip: "172.31.178.7"
  loopback: true
  interfaces:
    - name: "g0/1"
      ip: "172.31.178.66"
      subnet: "255.255.255.240"
      desc: "Connect to R3 and R5 (172.31.178.64/28)"
- name: S2
  id: 8
  management_ip: "172.31.178.8"
  loopback: true
  interfaces:
- name: R5
  id: 9
  management_ip: "172.31.178.9"
  loopback: true
  interfaces:
    - name: "g0/1"
      ip: "172.31.178.67"
      subnet: "255.255.255.240"
      desc: "Connect to R3 and R4 (172.31.178.64/28)"